name: Build Discord AppImage

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Last Built Version
        id: last_build
        run: echo "version=$(cat last_version.txt || echo '0.0.0')" >> $GITHUB_OUTPUT

      - name: Get Latest Discord Version
        id: get_latest_version
        run: |
          FINAL_URL=$(curl -s -L -w "%{url_effective}" -o /dev/null "https://discord.com/api/download?platform=linux&format=deb")
          VERSION=$(echo "$FINAL_URL" | grep -oP '(?<=linux/)[0-9]+\.[0-9]+\.[0-9]+')
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Latest available version is $VERSION"

      - name: Build AppImage
        id: build
        if: steps.get_latest_version.outputs.version != steps.last_build.outputs.version
        run: |
          echo "New version detected. Starting build..."
          chmod +x build-discord-appimage.sh
          ./build-discord-appimage.sh

      - name: Create Release and Commit Version
        if: steps.build.outputs.appimage_name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ steps.get_latest_version.outputs.version }}
          APPIMAGE_NAME=${{ steps.build.outputs.appimage_name }}

          gh release create "$VERSION" \
            --title "Release $VERSION" \
            --notes "Automatic release of Discord $VERSION" \
            "$APPIMAGE_NAME"

          echo "$VERSION" > last_version.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add last_version.txt
          git commit -m "chore: Update last built Discord version to $VERSION"
          git push

      - name: Log Skipped Build
        if: steps.get_latest_version.outputs.version == steps.last_build.outputs.version
        run: echo "No new Discord version detected. Skipping build."
